import { AssetContent, ContentGroupContainer } from "@repo/contentful/render";
import React from "react";

export const LandingPageComponentMap = {
  LdJson: (p) => <div>{p.fields?.name}</div>,
  FooterMenu: (p) => <div>{p.fields?.name}</div>,
  SignInModal: (p) => <div>{p.fields?.name}</div>,
  SignInFlyOut: (p) => <div>{p.fields?.name}</div>,
  SignInTabs: (p) => <div>{p.fields?.name}</div>,
  PageBreadcrumb: (p) => <div>{p.fields?.name}</div>,
  StaticHTML: (p) => <div>{p.fields?.name}</div>,
  StaticCSS: (p) => <div>{p.fields?.name}</div>,
  StaticJS: (p) => <div>{p.fields?.name}</div>,
  StaticJSCSS: (p) => <div>{p.fields?.name}</div>,
  SignOutFlyOut: (p) => <div>{p.fields?.name}</div>,
  SimplifiedHeader: (p) => <div>{p.fields?.name}</div>,
  DropDownOptionsGenerator: (p) => <div>{p.fields?.name}</div>,
  RFKPromoBanner: (p) => <div>{p.fields?.name}</div>,
  MessageRibbonRPP: (p) => <div>{p.fields?.name}</div>,
  UsableNetToggler: (p) => <div>{p.fields?.name}</div>,
  FireWorkLiveStream: (p) => <div>{p.fields?.name}</div>,
  AffirmPayJS: (p) => <div>{p.fields?.name}</div>,
  CRMOptIn: (p) => <div>{p.fields?.name}</div>,
  StaticMessageRibbon: (p) => <div>{p.fields?.name}</div>,
  AssetContent: AssetContent,
  GlobalHeader: (p) => <div>{p.fields?.name}</div>,
  Breadcrumb: (p) => <div>{p.fields?.name}</div>,
  AutoCorrect: (p) => <div>{p.fields?.name}</div>,
  MainSection: (p) => <div>{p.fields?.name}</div>,
  StaticProductList: (p) => <div>{p.fields?.name}</div>,
  BasicContentGroup: (p) => <div>{p.fields?.name}</div>,

  RecommendationCarousel: (p) => <div>{p.fields?.name}</div>,
  TrustBar: (p) => <div>{p.fields?.name}</div>,

  // new plp
  FlashSaleBanner: (p) => <div>{p.fields?.name}</div>,
  ContentGroupContainer: ContentGroupContainer,
  NewPLPFilter: (p) => <div>{p.fields?.name}</div>,
  NewPLPHeader: (p) => <div>{p.fields?.name}</div>,
  NewProductList: (p) => <div>{p.fields?.name}</div>,
  RewardsMessage: (p) => <div>{p.fields?.name}</div>,
  RewardsRibbon: (p) => <div>{p.fields?.name}</div>,
  PromoBanner: (p) => <div>{p.fields?.name}</div>,
  RelatedProducts: (p) => <div>{p.fields?.name}</div>,
  NewPLPSearchHeader: (p) => <div>{p.fields?.name}</div>,
  NoResultDescription: (p) => <div>{p.fields?.name}</div>,
  PLPHeaderBanner: (p) => <div>{p.fields?.name}</div>,
  ThemeBanner: (p) => <div>{p.fields?.name}</div>,
  ContactLensesVisualFilter: (p) => <div>{p.fields?.name}</div>,
  ContactMessageRibbon: (p) => <div>{p.fields?.name}</div>,
  DailyDealCarousel: (p) => <div>{p.fields?.name}</div>,
  DynamicVariationsPromo: (p) => <div>{p.fields?.name}</div>,
  CollapseWithAnimation: (p) => <div>{p.fields?.name}</div>,
};
